### ISSUE TITLE
RTL TCP doesn't work

### ISSUE THREAD

**Issue by rpatel3001** [airframesio/aero-cli#3]
changing the device string from `driver=rtlsdr,serial=00001542` to `driver=rtltcp,rtltcp=10.0.0.145:7374` causes no messages to be decoded. The rest of the setup is identical. The rtl_tcp instance is tuned correctly because a satdump instance connected to it with the center freq set the same gets messages ok.

**Comment by rpatel3001** [comment]
rtl_tcp:
```
  satmuxer:
    container_name: satmuxer
    hostname: satmuxer
    image: ghcr.io/rpatel3001/docker-rtlmuxer
    restart: always
    ports:
      - 7373:7373
      - 7374:7374
    device_cgroup_rules:
      - 'c 189:* rwm'
    volumes:
      - /dev:/dev:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - RTL_TCP=true
      - SERIAL=00001542
      - FREQ=1545600000
      - RATE=1536000
```

ini file:
```
#Main sample rate, do not change basically
sample_rate=1536000
#Tuning freq for the dongle, probably no reason to modify
center_frequency=1545600000
#This is the address ZMQ will band to for sending audio to jaero
zmq_address=tcp://*:6003
#Enable this to remove the annoying spike in the middle of the spectrum
correct_dc_bias=1

#valid tuner gains r82xx_gains[] = { 0, 9, 14, 27, 37, 77, 87, 125, 144, 157, 166, 197, 207, 229, 254, 280, 297, 328, 338, 364, 372, 386, 402, 421, 434, 439, 445, 480, 496 };
tuner_gain=496

#to raise or lower the center frequency of each VFO set a value here, i.e. -1000 to lower each VFO with 1000hz or 2000 to increase by 2000 hz. Useful when swichting dongles for instance.
mix_offset=0

#to start the SDR automatically set to 1
#auto_start=0
#auto_start_tuner_idx=0

#typically not needed to modify the below block. It is used to mix down the lower data rate and higher rate channels into into different chunks to improve decimatation performance
[main_vfos]
size=2
1\frequency=1545116000
1\out_rate=384000
2\frequency=1546096000
2\out_rate=192000
#Actual VFO's. When adding more just increase the size value on top. Ensure to keep the numbering sequence and formatting of variables, the application will probably crash otherwise
[vfos]
size=1
1\frequency=1546005000
1\gain=5
1\data_rate=10500
1\filter_bandwidth=0
1\topic=VFO01
```

satdump:
```
  satdump:
    container_name: satdump
    hostname: satdump
    image: ghcr.io/rpatel3001/docker-satdump:latest
    restart: always
    device_cgroup_rules:
      - 'c 189:* rwm'
    volumes:
      - /dev:/dev:rw
      - ./vfo.json:/vfo.json
      - ./Inmarsat.json:/usr/share/satdump/pipelines/Inmarsat.json
    environment:
#      - RUN_CMD=satdump live inmarsat_aero_6 /tmp/satdump_out --source rtltcp --ip_address 10.0.0.145 --port 7373 --gain 49 --samplerate 1.536e6 --frequency 1545.6e6 --multi_vfo /vfo.json --http_server 0.0.0.0:5000 2>&1 | grep -v "Invalid CRC!"
      - RUN_CMD=satdump live inmarsat_aero_6 /tmp/satdump_out --source rtltcp --ip_address 10.0.0.145 --port 7374 --gain 49 --samplerate 1.536e6 --frequency 1545.6e6 --multi_vfo /vfo.json --http_server 0.0.0.0:5000 2>&1 | grep -v "Invalid CRC!"
#      - RUN_CMD=satdump live inmarsat_aero_6 /tmp/satdump_out --source rtlsdr --source_id 00001542 --gain 49 --samplerate 1.536e6 --frequency 1545.6e6 --multi_vfo /vfo.json --http_server 0.0.0.0:5000 2>&1 | grep -v "Invalid CRC!"
      - STATION_ID=RP-KLDJ-IMSL-98W
      - JSON_OUT=acars_router:5557
      - OUTPUT_NONEMPTY_ONLY=true
      - LOG_RAW=true
#      - LOG_OUT_JSON_FILT=true
```
